language: c

before_install:
  - export SOURCE_DIR=`pwd`
  - sudo apt-get update -qq
  - sudo apt-get install -y scons git flex uuid-dev libevent-dev cmake git libzmq3-dev
  - cd
  - wget https://github.com/apache/qpid-proton/archive/0.10.tar.gz -O proton.tgz
  - tar xvf proton.tgz
  - cd qpid-proton*
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DSYSINSTALL_BINDINGS=ON -DBUILD_JAVA=OFF -DBUILD_PERL=OFF -DBUILD_PHP=OFF -DBUILD_PYTHON=OFF -DBUILD_RUBY=OFF
  - sudo make install
  - cd
  - git clone https://github.com/fquinner/OpenMAMA.git
  - cd OpenMAMA
  - git checkout feature-omzmq
  - scons product=mama middleware=qpid
  - export MAMA_SOURCE=$(pwd)
  - export MAMA_INSTALL=$MAMA_SOURCE/$(ls -1 | grep "openmama_install_*")

script:
 - cd $SOURCE_DIR
 - scons --with-mamasource=$MAMA_SOURCE --with-mamainstall=$MAMA_INSTALL